spring.application.name=BookMarket
server.servlet.context-path=/bookmarket
spring.servlet.multipart.max-file-size=200MB
spring.servlet.multipart.max-request-size=215MB

spring.servlet.multipart.resolve-lazily=true

server.tomcat.max-http-form-post-size=2147483647 
server.tomcat.max-swallow-size=2147483647

file.uploadDir=C:/upload/

# 삭제하세요 이유는 모름?
# spring.servlet.multipart.enabled=true
# spring.servlet.multipart.file-size-threshold=2KB
# spring.servlet.multipart.location=C:/upload */

